# Extract a frame sequence from public/hero.mp4 into public/frames/ (desktop)
# and public/frames-mobile/ (half-res), then write a manifest.json.
# Run from repo root: pwsh tools/extract-frames.ps1
$ErrorActionPreference = 'Stop'

$root        = Resolve-Path "$PSScriptRoot\.."
$source      = Join-Path $root 'public\hero.mp4'
$framesDir   = Join-Path $root 'public\frames'
$mobileDir   = Join-Path $root 'public\frames-mobile'
$manifestOut = Join-Path $root 'src\components\sections\Hero\frameManifest.generated.js'
$ffmpeg      = Join-Path $root 'node_modules\ffmpeg-static\ffmpeg.exe'

if (!(Test-Path $source)) { throw "Source video not found: $source" }
if (!(Test-Path $ffmpeg)) { throw "ffmpeg-static not found. Run 'npm install' first." }

Remove-Item -Recurse -Force -ErrorAction SilentlyContinue $framesDir, $mobileDir
New-Item -ItemType Directory -Force -Path $framesDir, $mobileDir | Out-Null

Write-Host "Extracting desktop frames (1920x1080 @ 15fps -> webp q80)"
# -f image2 is required so libwebp emits per-frame stills, not one animated WebP.
& $ffmpeg -y -hide_banner -loglevel error -i $source `
    -vf "fps=15,scale=1920:1080:flags=lanczos" -c:v libwebp -q:v 80 -f image2 `
    (Join-Path $framesDir 'frame_%04d.webp')
if ($LASTEXITCODE -ne 0) { throw "ffmpeg desktop extract failed" }

Write-Host "Extracting mobile frames (960x540 @ 12fps -> webp q75)"
& $ffmpeg -y -hide_banner -loglevel error -i $source `
    -vf "fps=12,scale=960:540:flags=lanczos" -c:v libwebp -q:v 75 -f image2 `
    (Join-Path $mobileDir 'frame_%04d.webp')
if ($LASTEXITCODE -ne 0) { throw "ffmpeg mobile extract failed" }

# Generate the JS manifest the runtime imports.
$desktop = Get-ChildItem $framesDir -Filter 'frame_*.webp' | Sort-Object Name |
    ForEach-Object { "  '/frames/$($_.Name)'" }
$mobile  = Get-ChildItem $mobileDir -Filter 'frame_*.webp' | Sort-Object Name |
    ForEach-Object { "  '/frames-mobile/$($_.Name)'" }

$content = @"
// AUTO-GENERATED by tools/extract-frames.ps1 — do not edit by hand.
export const heroFrameManifest = [
$($desktop -join ",`n")
]

export const heroFrameManifestMobile = [
$($mobile -join ",`n")
]
"@

Set-Content -Encoding utf8 -Path $manifestOut -Value $content
Write-Host "Wrote manifest: $manifestOut ($($desktop.Count) desktop / $($mobile.Count) mobile frames)"
Write-Host "Update frameManifest.js to re-export from frameManifest.generated.js to activate."
